parameters:
    pipelines_dir: '%kernel.project_dir%/pipelines'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/'
            - '../src/Kernel.php'

    # Port bindings
    App\Application\Port\PipelineRepositoryPort:
        class: App\Infrastructure\Persistence\Yaml\YamlFilePipelineRepository
        arguments:
            $pipelinesDir: '%pipelines_dir%'

    App\Application\Port\PipelineRunRepositoryPort:
        class: App\Infrastructure\Persistence\Doctrine\DoctrinePipelineRunRepository

    App\Application\Port\ExecutorPort:
        class: App\Infrastructure\Executor\FakeExecutorAdapter

    App\Infrastructure\Http\Controller\ListPipelinesController:
        arguments:
            $pipelinesDir: '%pipelines_dir%'
