/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as PipelinesIndexRouteImport } from './routes/pipelines/index'
import { Route as PipelinesPipelineIdIndexRouteImport } from './routes/pipelines/$pipelineId/index'
import { Route as PipelinesPipelineIdRunsRunIdRouteImport } from './routes/pipelines/$pipelineId/runs/$runId'

const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesIndexRoute = PipelinesIndexRouteImport.update({
  id: '/pipelines/',
  path: '/pipelines/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesPipelineIdIndexRoute =
  PipelinesPipelineIdIndexRouteImport.update({
    id: '/pipelines/$pipelineId/',
    path: '/pipelines/$pipelineId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PipelinesPipelineIdRunsRunIdRoute =
  PipelinesPipelineIdRunsRunIdRouteImport.update({
    id: '/pipelines/$pipelineId/runs/$runId',
    path: '/pipelines/$pipelineId/runs/$runId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/pipelines/': typeof PipelinesIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/pipelines/$pipelineId/': typeof PipelinesPipelineIdIndexRoute
  '/pipelines/$pipelineId/runs/$runId': typeof PipelinesPipelineIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/pipelines': typeof PipelinesIndexRoute
  '/runs': typeof RunsIndexRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdIndexRoute
  '/pipelines/$pipelineId/runs/$runId': typeof PipelinesPipelineIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/pipelines/': typeof PipelinesIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/pipelines/$pipelineId/': typeof PipelinesPipelineIdIndexRoute
  '/pipelines/$pipelineId/runs/$runId': typeof PipelinesPipelineIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground'
    | '/pipelines/'
    | '/runs/'
    | '/pipelines/$pipelineId/'
    | '/pipelines/$pipelineId/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/pipelines'
    | '/runs'
    | '/pipelines/$pipelineId'
    | '/pipelines/$pipelineId/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/playground'
    | '/pipelines/'
    | '/runs/'
    | '/pipelines/$pipelineId/'
    | '/pipelines/$pipelineId/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PipelinesIndexRoute: typeof PipelinesIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  PipelinesPipelineIdIndexRoute: typeof PipelinesPipelineIdIndexRoute
  PipelinesPipelineIdRunsRunIdRoute: typeof PipelinesPipelineIdRunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/': {
      id: '/pipelines/'
      path: '/pipelines'
      fullPath: '/pipelines/'
      preLoaderRoute: typeof PipelinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/$pipelineId/': {
      id: '/pipelines/$pipelineId/'
      path: '/pipelines/$pipelineId'
      fullPath: '/pipelines/$pipelineId/'
      preLoaderRoute: typeof PipelinesPipelineIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/$pipelineId/runs/$runId': {
      id: '/pipelines/$pipelineId/runs/$runId'
      path: '/pipelines/$pipelineId/runs/$runId'
      fullPath: '/pipelines/$pipelineId/runs/$runId'
      preLoaderRoute: typeof PipelinesPipelineIdRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaygroundRoute: PlaygroundRoute,
  PipelinesIndexRoute: PipelinesIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  PipelinesPipelineIdIndexRoute: PipelinesPipelineIdIndexRoute,
  PipelinesPipelineIdRunsRunIdRoute: PipelinesPipelineIdRunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
